const {
  seachByHealthId,
  generateAadhaarOtp,
  resendAadhaarOtp,
  verifyAadhaarOtp,
  checkAndGenerateMobileOtp,
  verifyMobileOtp,
  createHealthId,
  initLoginAadhaar,
  loginWithPassword,
  verifyAadhaarOtpLogin,
  generateMobileOtpLogin,
  userAuthorizedToken,
  deleteAccountGenerateOtp,
  deleteAccountVerifyOtp,
  changePasswordRequestBody,
  changePasswordUpdate,
  verifyDeactivateAccount,
  generateXTokenFromRefreshToken,
  changeEmailInit,
  changeEmailVerify,
  changeMobileVerificationInit,
  changeMobileVerificationNewVerify,
  changeMobileVerifyOldByAadhaarInit,
  changeMobileVerifyOldByMobileInit,
  changeMobileVerifyOld,
  verifyUserToken,
  deactivateAccountByAadhaarInit,
  resendMobileOtp,
  checkHealthId,
  generateAbhaOtpLogin,
  abhaLoginWithAadhaarOtp,
  abhaLoginWithMobileOtp,
  resendAuthOtp,
  emptyBody,
  forgotAbhaGenerateMobileOtp,
  forgotAbhaVerifyMobileOtp,
  forgotAbhaGenerateAadhaarOtp,
  forgotAbhaVerifyAadhaarOtp,
  forgotAbhaResendAadhaarOtp,
  reactivateAuthInit,
  reactivateAuthVerify
} = require('../schemas/healthId')

const pathMap = {
  '/v1/search/searchByHealthId': seachByHealthId,
  '/v2/registration/aadhaar/generateOtp': generateAadhaarOtp,
  '/v1/registration/aadhaar/resendAadhaarOtp': resendAadhaarOtp,
  '/v2/registration/aadhaar/verifyOTP': verifyAadhaarOtp,
  '/v2/registration/aadhaar/checkAndGenerateMobileOTP':
    checkAndGenerateMobileOtp,
  '/v2/registration/aadhaar/verifyMobileOTP': verifyAadhaarOtp,
  '/v1/registration/aadhaar/createHealthIdWithPreVerified': createHealthId,
  '/v1/auth/init': initLoginAadhaar,
  '/v1/registration/aadhaar/verifyMobileOTP': verifyAadhaarOtp,
  '/v1/auth/confirmWithAadhaarOtp': verifyAadhaarOtpLogin,
  '/v2/registration/mobile/login/generateOtp': generateMobileOtpLogin,
  '/v2/auth/confirmWithPassword': loginWithPassword,
  '/v2/registration/mobile/login/verifyOtp': verifyMobileOtp,
  '/v2/registration/mobile/login/userAuthorizedToken': userAuthorizedToken,
  '/v2/account/mobile/generateOTP': deleteAccountGenerateOtp,
  '/v2/account/profile/delete': deleteAccountVerifyOtp,
  '/v1/account/change/passwd/generateAadhaarOTP': emptyBody,
  '/v1/account/change/passwd/generateMobileOTP': emptyBody,
  '/v1/account/change/password': changePasswordRequestBody,
  '/v1/account/change/passwd/byAadhaar': changePasswordUpdate,
  '/v1/account/change/passwd/byMobile': changePasswordUpdate,
  '/v2/account/profile/deactivate': verifyDeactivateAccount,
  '/v1/auth/generate/access-token': generateXTokenFromRefreshToken,
  '/v2/account/email/verification/auth/initiate/send': changeEmailInit,
  '/v2/account/email/verification/auth/verify': changeEmailVerify,
  '/v2/account/change/mobile/new/generateOTP': changeMobileVerificationInit,
  '/v2/account/change/mobile/new/verifyOTP': changeMobileVerificationNewVerify,
  '/v2/account/change/mobile/aadhaar/generateOTP':
    changeMobileVerifyOldByAadhaarInit,
  '/v2/account/change/mobile/old/generateOTP':
    changeMobileVerifyOldByMobileInit,
  '/v2/account/change/mobile/update/authentication': changeMobileVerifyOld,
  '/v1/account/token': verifyUserToken,
  '/v2/account/aadhaar/generateOTP': deactivateAccountByAadhaarInit,
  '/v2/registration/mobile/login/resendOtp': resendMobileOtp,
  '/v2/search/searchHealthIdToLogin': checkHealthId,
  '/v2/auth/init': generateAbhaOtpLogin,
  '/v2/auth/confirmWithAadhaarOtp': abhaLoginWithAadhaarOtp,
  '/v2/auth/confirmWithMobileOTP': abhaLoginWithMobileOtp,
  '/v1/auth/resendAuthOTP': resendAuthOtp,
  '/v2/account/profile': true,
  '/v1/account/qrCode': true,

  // FORGOT ABHA
  '/v2/forgot/healthId/mobile/generateOtp': forgotAbhaGenerateMobileOtp,
  '/v2/forgot/healthId/mobile': forgotAbhaVerifyMobileOtp,
  '/v2/forgot/healthId/aadhaar/generateOtp': forgotAbhaGenerateAadhaarOtp,
  '/v2/forgot/healthId/aadhaar': forgotAbhaVerifyAadhaarOtp,
  '/v2/registration/aadhaar/resendAadhaarOtp': forgotAbhaResendAadhaarOtp,
  '/v2/auth/reactivate/init': reactivateAuthInit,
  '/v2/auth/reactivate': reactivateAuthVerify
}

module.exports = pathMap
